services:
  yaci:
    build:
      context: ./src/yaci
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  postgres:
    image: postgres:16.1-bullseye
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  pgadmin:
    # image: dpage/pgadmin4
    build:
      context: ./src/pgadmin
      args:
        NETWORK: ${NETWORK}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    environment:
        PGADMIN_LISTEN_PORT: 80
    ports:
        - "${PGADMIN_PORT:-5050}:80"
    volumes:
        - ./pgadmin-data:/var/lib/pgadmin
